n = int(input('Digite qualquer número inteiro: '))
tabuada1 = (n*1)
tabuada2 = (n*2)
tabuada3 = (n*3)
tabuada4 = (n*4)
tabuada5 = (n*5)
tabuada6 = (n*6)
tabuada7 = (n*7)
tabuada8 = (n*8)
tabuada9 = (n*9)
tabuada10 = (n*10)
print(f'A tabuada de {n} é: \n {n} x 1 = {tabuada1} \n {n} x 2 = {tabuada2} \n {n} x 3 = {tabuada3} \n {n} x 4 = {tabuada4} \n {n} x 5 = {tabuada5} \n {n} x 6 = {tabuada6} \n {n} x 7 = {tabuada7} \n {n} x 8 = {tabuada8} \n {n} x 9 = {tabuada9} \n {n} x 10 = {tabuada10} ')