altura = int(input('Digite a altura da parede: '))
largura = int(input('Digite a largura da parede: '))
area = (altura*largura)
tinta = (area//2)
print (f'Para pintar a parede serão necessárias aproximadamente {tinta} latas de tinta.')